/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.testng.annotations.Test;

public class AppTest {
    @Test public void appHasAGreeting() {
        
    }
}
